---
services: docker

env:
  # Run each method in a separate environment.
  - method: drupal-quick-start.sh
  - method: composer-drupal-vm.sh
  - method: lando.sh
  - method: ddev-local.sh

  # Can't test in Travis: https://github.com/travis-ci/travis-ci/issues/6060
  # - method: drupal-vm-composer.sh

before_script:
  - phpenv config-add tests/travis.php.ini
  - sudo netstat -tulpn

script:
  # Run tests.
  - cd ${PWD}/methods
  - ./${method}
